version: '3.8'
services:
  frigate-telegram-record:
    image: ghcr.io/silverknightkma/frigate-telegram-record:v1.2.3
    container_name: frigate-telegram-record
    restart: unless-stopped
    tmpfs:
      - /dev/shm:rw,size=512m
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - BOT_TOKEN=your_telegram_bot_token_here
      - CAMERAS=Readable_name|camera_id|thread_id|chat_id;Backyard|backyard|23|-100xxxxxxx
      - ERROR_CHAT_ID=-100xxxxxxx
      - FRIGATE_HOST=http://192.168.1.x:5000

  frigate-telegram-timelapse:
    image: ghcr.io/silverknightkma/frigate-telegram-record:v1.2.3
    container_name: frigate-telegram-timelapse
    restart: unless-stopped
    tmpfs:
      - /dev/shm:rw,size=1G
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MODE=timelapse
      - BOT_TOKEN=your_telegram_bot_token_here
      - CAMERAS=Readable_name|camera_id|thread_id|chat_id;Backyard|backyard|23|-100xxxxxxx
      - ERROR_CHAT_ID=-100xxxxxxx
      - FRIGATE_HOST=http://192.168.1.x:5000

  frigate-web-dashboard:
    image: ghcr.io/silverknightkma/frigate-telegram-record-web:v1.2.2
    container_name: frigate-web-dashboard
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_FILE=/app/data/video_history.sqlite
      - WEB_PORT=8080